### PR TITLE
Bug Fixes on sd reading and added force installetion

### PR DESCRIPTION
**Pull request by erikiorai**

### CODE REVIEW

**Comment by KcrPL** [comment]
Cool, it added few features but i'm gonna close it and add it manually to patcher.

1) You broke SD Card part. Program is now set to "make" SD Card useable only if variable is set to 2. You made it set to 1.
2) Grammar errors.
3) We don't want peoples to force patch IOS's for Wii U. This may brick Wii mode in Wii U or even make it unbootable.

**Comment by erikiorai** [comment]
but in windox xp for me gives that error on vm

**Comment by erikiorai** [comment]
Ops *windows xp

**Comment by KcrPL** [comment]
What error? Can you give me screenshot?

**Comment by erikiorai** [comment]
Error code:2146232576

**Comment by KcrPL** [comment]
Read carefully what is on screen.

>Please install .NET Framework 3.5, than try to patch again.

**Comment by erikiorai** [comment]
A ok

**Pull request closed without merging**
