### PR TITLE
UpdateServer is better then FileHostedOn

### PR DESCRIPTION
**Pull request by erikiorai**
Change %FileHostedOn% to %UpdateServer%

### CODE REVIEW

**Comment by KcrPL** [comment]
No.

**Comment by KcrPL** [comment]
It changed nothing, only the variable name ;__;

**Comment by erikiorai** [comment]
Its not better UpdateServer and why?

**Comment by KcrPL** [comment]
1) I'm currently working on update so there's no way i'm merging it.
2) Does somebody care about how it's named? When your running patch.bat, nobody can see it.
3) FilesHostedOn because it contains the info about where the FilesAreHostedOn. ;)

**Comment by erikiorai** [comment]
Ok thanks

**Comment by KcrPL** [comment]
Your welcome.

**Pull request closed without merging**
